name: some

on:
  push:
    branches:
      - main
      - stage

jobs:
  test-job:
    uses: Coalery/ruleset-test/.github/workflows/test-env-share.yaml@stage

  other-job:
    uses: Coalery/ruleset-test/.github/workflows/test-env-share.yaml@stage

  another-job:
    uses: Coalery/ruleset-test/.github/workflows/test-env-share.yaml@stage
