name: some

on:
  push:
    branches:
      - main
      - stage

jobs:
  lock-stage:
    name: Lock stage
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'

    outputs:
      RULESET_ID: ${{ steps.locking.outputs.RULESET_ID }}

    steps:
      - name: Lock stage branch with ruleset
        id: locking
        run: |
          response=$(curl -s -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer ${{ secrets.API_PAT }}" \
            https://api.github.com/repos/${{ github.repository }}/rulesets \
            -d '{"name":"Lock until deploy completed","enforcement":"active","target":"branch","bypass_actors":[{"actor_id":5,"actor_type":"RepositoryRole","bypass_mode":"always"}],"conditions":{"ref_name":{"include":["refs/heads/stage"],"exclude":[]}},"rules":[{"type":"update"}]}')
          echo $response

          rulesetId=$(echo $response | jq -r '.id')
          echo "$rulesetId"
          echo "RULESET_ID=$rulesetId" >> $GITHUB_OUTPUT

  test-job:
    name: Test job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: npm ci
      - name: Wait 3 seconds
        run: sleep 3
      - name: Semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}

  release-stage:
    name: "Release stage"
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'

    needs:
      - lock-stage
      - test-job

    steps:
      - name: Release lock from stage
        run: |
          echo "RULESET_ID=${{ needs.lock-stage.outputs.RULESET_ID }}"
          curl -s -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer ${{ secrets.API_PAT }}" \
            https://api.github.com/repos/${{ github.repository }}/rulesets/${{ needs.lock-stage.outputs.RULESET_ID }}
