name: test-env-share-across-several-calls

on: workflow_call

jobs:
  create-uuid:
    runs-on: ubuntu-latest
    steps:
      - name: Create UUID
        id: create-uuid
        run: |
          echo "${{ github.run_id }}"
